'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Recipes", [
      {
        name: 'Crispy fried chicken',
        info: '',
        calories: 300,
        proteins: 20,
        fats: 30,
        carbo: 10,
        idType: 1,points: 0,
        image: 'https://cdn.tgdd.vn/2020/08/CookRecipe/Avatar/uc-ga-chien-gion-thumbnail.jpg',
      },
      {
        name: 'Boiled Eggs',
        info: '',
        calories: 200,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'http://t1.gstatic.com/licensed-image?q=tbn:ANd9GcQkn_6Y0-g8lFMQ2asrd3VTy4SOeDei_LEMXDxUTPsz5FjOJTuNn-uqmh33IwtTkGs90cfLOGkaTdgnT_1xEno',
      },
      {
        name: 'Boiled Chicken',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Sauteed chicken breast',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 1,points: 0,
        image: 'https://img.tastykitchen.vn/resize/764x-/2021/03/27/ga-xao-mang-tay-f24a.jpg',
      },
      {
        name: 'Boiled Chicken3',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken4',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken5',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken6',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken7',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken8',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken9',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken10',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken11',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken12',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken13',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken14',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken15',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken16',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken17',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken18',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken19',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Boiled Chicken20',
        info: '',
        calories: 400,
        proteins: 40,
        fats: 30,
        carbo: 10,
        idType: 2,points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Grilled Salmon1',
        info: '',
        calories: 350,
        proteins: 35,
        fats: 25,
        carbo: 15,
        idType: 2,
        points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Roasted Turkey2',
        info: '',
        calories: 360,
        proteins: 36,
        fats: 26,
        carbo: 16,
        idType: 2,
        points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Baked Cod3',
        info: '',
        calories: 370,
        proteins: 37,
        fats: 27,
        carbo: 17,
        idType: 2,
        points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Fried Tofu4',
        info: '',
        calories: 380,
        proteins: 38,
        fats: 28,
        carbo: 18,
        idType: 2,
        points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Grilled Salmon',
        info: '',
        calories: 350,
        proteins: 35,
        fats: 25,
        carbo: 15,
        idType: 2,
        points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Roasted Turkey',
        info: '',
        calories: 360,
        proteins: 36,
        fats: 26,
        carbo: 16,
        idType: 2,
        points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Baked Cod',
        info: '',
        calories: 370,
        proteins: 37,
        fats: 27,
        carbo: 17,
        idType: 2,
        points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
      {
        name: 'Fried Tofu',
        info: '',
        calories: 380,
        proteins: 38,
        fats: 28,
        carbo: 18,
        idType: 2,
        points: 0,
        image: 'https://cdn.tgdd.vn/2021/01/CookProduct/cach-lam-ga-cung4-960x540.jpg',
      },
    ]);
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
